import type { Metadata } from "next";
import "@/assets/base/main.scss";
import Header from "@/ui/organisms/Header/Header";
import { Footer } from "@/ui/organisms";
import "../../globals.scss";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function LayoutPublic({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
    <Header />
    {children}
    <Footer />
    </>
  );
}
