import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.scss";
import "@/assets/base/main.scss";

const neulisRegularFont = localFont({
  src: "./fonts/Neulis-regular.woff",
  variable: "--font-neulis",
  weight: "100 900",
});

const neulisMediumFont = localFont({
  src: "./fonts/Neulis-regular.woff",
  variable: "--font-neulis-regular",
  weight: "100 900",
});

const neulisBoldFont = localFont({
  src: "./fonts/Neulis-bold.woff",
  variable: "--font-neulis-bold",
  weight: "100 900",
});

const clashDisplayBold = localFont({
  src: "./fonts/ClashDisplay-Bold.woff",
  variable: "--font-clash-display-bold",
  weight: "100 900",
});

const clashDisplayRegular = localFont({
  src: "./fonts/ClashDisplay-Regular.woff",
  variable: "--font-clash-display-regular",
  weight: "100 900",
});

const clashDisplayMedium = localFont({
  src: "./fonts/ClashDisplay-Medium.woff",
  variable: "--font-clash-display-medium",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${neulisBoldFont.variable} 
                        ${neulisRegularFont.variable} 
                        ${neulisMediumFont.variable} 
                        ${clashDisplayBold.variable} 
                        ${clashDisplayRegular.variable} 
                        ${clashDisplayMedium.variable}`}>
        {children}
      </body>
    </html>
  );
}
