import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.scss";
import "@/assets/base/main.scss";

const neulisRegularFont = localFont({
  src: "./fonts/Neulis-regular.woff",
  variable: "--font-neulis",
  weight: "100 900",
});

const neulisMediumFont = localFont({
  src: "./fonts/Neulis-regular.woff",
  variable: "--font-neulis-regular",
  weight: "100 900",
});

const neulisBoldFont = localFont({
  src: "./fonts/Neulis-bold.woff",
  variable: "--font-neulis-bold",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${neulisBoldFont.variable} ${neulisRegularFont.variable} ${neulisMediumFont.variable}`}>
        {children}
      </body>
    </html>
  );
}
