import { Button } from "@/ui/atoms";
import type { Metadata } from "next";
import { cookies } from "next/headers";
import "../../globals.scss";
import "./dashboardStyles.scss";
import { Dashboard } from "@/ui/templates";
import { Sidebar } from "@/ui/organisms";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function LayoutDashboard({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = cookies();
  const tokenLogin:string | undefined = cookieStore.get("TOKEN_LOGGED_USER")?.value;
  const tokenRegister:string | undefined = cookieStore.get("TOKEN_REGISTERED_USER")?.value;
  return (
    <div className="dashboard">
      <Sidebar/>
      <Dashboard />
    </div>
  );
}
